name: ConfAnalysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # 降低版本以提高兼容性
  - requests
  - beautifulsoup4
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - nltk
  - lxml
  - tqdm
  - pip
  - pip:
    - wordcloud
    - plotly
    - selenium
    - webdriver-manager
    # PDF processing
    - PyPDF2
    - pymupdf
    - aiofiles
    - aiohttp
    # Vector database and embeddings
    - pymilvus
    - sentence-transformers
    - torch
    - transformers